### ISSUE TITLE
Add native authentication with Google

### ISSUE THREAD

**Issue by embray** [hayj/Renewal#14]
Expo provides a couple different interfaces for authenticating with Google:

1. The first is web redirection based: The Google login page is presented in a web view, completed there, and then the login credentials are sent back to the app.  Usually this works, although sometimes it doesn't: If the phone is running on low memory it's possible that the Expo app gets swapped out of memory and has to restart after returning from the login page.  At this point the app restarts and it fails to continue the login process.  I would like to see if there is a workaround for this but I am not sure.  When running the app through Expo this is the only method supported.

2. There is also a native interface for Google authentication (at least on Android; I'm not sure about iOS).  In this case a native widget is provided for authenticating with Google through any Google accounts the user has registered on the device (if any, though on Android there usually is one).  This method is available if the app is built in stand-alone mode (that is, not running through Expo).  This is of course the usual way users will use the app so it should work.

Currently only method 1 is supported in the Renewal app since I have been developing and testing in Expo's hosted mode.  The native method does not work in this case--I believe it has something to do with the app itself having to have a unique ID for interacting with Google through the OS, and this is not possible when running in Expo because it's the Expo app itself that the app is running in, and so it cannot provide this unique identification.

This issue is a reminder to implement method 2, for which I will also have to test building and running the app in stand-alone mode (which needs to be done anyways since this is ultimately how it will be distributed through the app store).

**Comment by hayj** [comment]
But Firebase doesn't provide something simpler?
What about this? https://rnfirebase.io/

**Comment by embray** [comment]
Yes I'm already using the firebase support provided through Expo.  This is just a question of the UI presented to users to log into their Google account.  It's just to use the native UI you have to build the app as a stand-alone APK instead of running it through Expo. That's all.

**Comment by embray** [comment]
Fixed in my fork by 072f9ee
